import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { Command } from 'commander';

const _require = createRequire(import.meta.url);
// omelette is a CJS module with no @types package
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const omelette = _require('omelette') as (template: string) => any;

// Profile slugs per cli-autocomplete spec: 19 canonical + 3 legacy aliases.
// Reference: platform-profiles spec for canonical slug definitions.
const PROFILE_SLUGS = [
  // LinkedIn
  'linkedin-background',
  'linkedin-post',
  'linkedin-article-cover',
  'linkedin-profile',
  'linkedin-single-image-ad',
  'linkedin-career-background',
  // Twitter/X
  'twitter-post',
  'twitter-header',
  'twitter-ad',
  'twitter-video',
  'twitter-ad-landscape',
  // Instagram
  'instagram-post-3-4',
  'instagram-post-4-5',
  'instagram-post-square',
  'instagram-story',
  'instagram-reel',
  'instagram-profile',
  'instagram-story-video',
  // Generic
  'square',
  // Legacy aliases — resolved server-side to canonical slugs
  'linkedin',
  'twitter',
  'instagram',
];

const FORMAT_VALUES = ['png', 'jpeg', 'webp', 'gif', 'mp4', 'webm'];

const CONVERT_FLAGS = [
  '--html',
  '--file',
  '--url',
  '--image',
  '--profile',
  '--output',
  '--format',
  '--quality',
  '--width',
  '--height',
  '--auto-size',
  '--fps',
  '--duration',
  '--selector',
  '--auto',
  '--allow-local',
];

// Flags that consume the next token as their value. All others are boolean (flag-position).
const VALUE_TAKING_FLAGS = new Set([
  '--profile', '--format', '--url', '--html', '--file',
  '--image', '--output', '--width', '--height', '--quality',
  '--fps', '--duration', '--selector',
]);

/**
 * Generates a fish completion file for pixdom.
 *
 * omelette's --completion-fish output does not enable path completion for --file/--image.
 * This function emits a complete fish completion file that uses -F (force-files) on those
 * two flags so fish falls back to native filename completion for their arguments.
 */
function generateFishCompletionScript(): string {
  const lines: string[] = [
    '# pixdom fish completion',
    '# Generated by: pixdom completion',
    '',
    '# Disable file completion by default (re-enabled per-flag where needed)',
    'complete -c pixdom -f',
    '',
    '# Subcommands',
    'complete -c pixdom -n "__fish_use_subcommand" -a convert -d "Render HTML, file, or URL to image/video"',
    'complete -c pixdom -n "__fish_use_subcommand" -a completion -d "Print shell completion script"',
    'complete -c pixdom -n "__fish_use_subcommand" -a mcp -d "Manage MCP server integration"',
    '',
    '# Global flags',
    'complete -c pixdom -l no-color -d "Disable ANSI color in error output"',
    'complete -c pixdom -l no-progress -d "Disable progress spinner output"',
    '',
    '# convert flags — free-text / numeric (no value completion)',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l html -r -d "Inline HTML string"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l url -r -d "Remote URL to render"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l output -r -d "Output file path"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l width -r -d "Viewport width in pixels"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l height -r -d "Viewport height in pixels"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l quality -r -d "Compression quality 0-100"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l fps -r -d "Frame rate for animated output"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l duration -r -d "Animation cycle length in ms"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l auto-size -d "Auto-detect output dimensions"',
    '',
    '# convert --file and --image: path completion via -F (force-files)',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l file -r -F -d "Local HTML file path"',
    'complete -c pixdom -n "__fish_seen_subcommand_from convert" -l image -r -F -d "Local image file to convert"',
    '',
    '# convert --format values',
    ...FORMAT_VALUES.map(
      (v) =>
        `complete -c pixdom -n "__fish_seen_subcommand_from convert" -l format -r -a "${v}" -d "Output format"`,
    ),
    '',
    '# convert --profile values',
    ...PROFILE_SLUGS.map(
      (v) =>
        `complete -c pixdom -n "__fish_seen_subcommand_from convert" -l profile -r -a "${v}"`,
    ),
    '',
    '# completion subcommand flags',
    'complete -c pixdom -n "__fish_seen_subcommand_from completion" -l install -d "Print installation instructions"',
    '',
    '# pixdom-mcp: disable file completion (binary takes no arguments)',
    "complete -c pixdom-mcp -f -n 'true'",
    '',
    '# mcp subcommand flags',
    'complete -c pixdom -n "__fish_seen_subcommand_from mcp" -l install -d "Install MCP server"',
    'complete -c pixdom -n "__fish_seen_subcommand_from mcp" -l uninstall -d "Uninstall MCP server"',
    'complete -c pixdom -n "__fish_seen_subcommand_from mcp" -l status -d "Show MCP server status"',
    'complete -c pixdom -n "__fish_seen_subcommand_from mcp" -l set-key -r -d "Set API key for MCP server"',
    'complete -c pixdom -n "__fish_seen_subcommand_from mcp" -l help -d "Show MCP help"',
  ];
  return lines.join('\n') + '\n';
}

/**
 * Generates a correct bash/zsh completion init script.
 *
 * omelette's generateCompletionCode() wraps the bash -W wordlist in single quotes,
 * preventing the $(pixdom --compbash ...) command substitution from ever executing.
 * This function emits the same structure with the bash block fixed to use a local
 * variable so the substitution runs correctly.
 */
function generateCompletionScript(program: string): string {
  const fn = `_${program}_completion`;
  return [
    `### ${program} completion - begin ###`,
    `if type compdef &>/dev/null; then`,
    `  ${fn}() {`,
    `    local _${program}_comps`,
    `    local -a _${program}_arr`,
    `    _${program}_comps=$(${program} --compzsh --compgen "\${CURRENT}" "\${words[CURRENT-1]}" "\${BUFFER}")`,
    `    if [[ -n "$_${program}_comps" ]]; then`,
    `      _${program}_arr=("\${(@f)_${program}_comps}")`,
    `      compadd -a _${program}_arr`,
    `    else`,
    `      _path_files`,
    `    fi`,
    `  }`,
    `  compdef ${fn} ${program}`,
    `  _pixdom_mcp_noop() { compadd -x 'pixdom-mcp takes no arguments'; return 0; }`,
    `  compdef _pixdom_mcp_noop pixdom-mcp`,
    `elif type complete &>/dev/null; then`,
    `  ${fn}() {`,
    `    local cur prev nb_colon _${program}_comps`,
    `    _get_comp_words_by_ref -n : cur prev`,
    `    nb_colon=$(grep -o ":" <<< "$COMP_LINE" | wc -l)`,
    `    _${program}_comps=$(${program} --compbash --compgen "$((COMP_CWORD - (nb_colon * 2)))" "$prev" "\${COMP_LINE}")`,
    `    COMPREPLY=( $(compgen -W "$_${program}_comps" -- "$cur") )`,
    `    __ltrim_colon_completions "$cur"`,
    `  }`,
    `  complete -F ${fn} -o default ${program}`,
    `  _pixdom_mcp_noop() { COMPREPLY=(); return 0; }`,
    `  complete -F _pixdom_mcp_noop -o nospace -o nosort pixdom-mcp`,
    `fi`,
    `### ${program} completion - end ###`,
  ].join('\n');
}

const BEGIN_MARKER = '### pixdom completion - begin ###';
const END_MARKER = '### pixdom completion - end ###';

/**
 * Replaces a hardcoded completion block (begin/end markers) in rc file content
 * with a single dynamic source line, or appends the line if no block exists.
 * Returns the updated content and whether a change was made.
 */
function upsertRcLine(content: string, sourceLine: string): { updated: string; changed: boolean } {
  const beginIdx = content.indexOf(BEGIN_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (beginIdx !== -1 && endIdx !== -1) {
    // Replace entire block (including surrounding newlines) with the single source line
    const before = content.slice(0, beginIdx).replace(/\n+$/, '');
    const after = content.slice(endIdx + END_MARKER.length).replace(/^\n+/, '');
    return { updated: `${before}\n${sourceLine}\n${after}`, changed: true };
  }

  if (content.includes(sourceLine)) {
    return { updated: content, changed: false };
  }

  const sep = content.endsWith('\n') ? '' : '\n';
  return { updated: `${content}${sep}${sourceLine}\n`, changed: true };
}

function installCompletion(): void {
  const shell = process.env.SHELL ?? '';
  const isBash = shell.includes('bash');
  const isZsh = shell.includes('zsh');
  const isFish = shell.includes('fish');

  if (isFish) {
    const dir = join(homedir(), '.config', 'fish', 'completions');
    const file = join(dir, 'pixdom.fish');
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, generateFishCompletionScript(), 'utf8');
    process.stdout.write(`✔ Fish completion written to ${file}\n`);
    process.stdout.write('Restart your terminal or run: source ' + file + '\n');
    return;
  }

  if (isBash || isZsh) {
    const rcFile = join(homedir(), isBash ? '.bashrc' : '.zshrc');
    const sourceLine = isZsh
      ? 'source <(pixdom --completion)'
      : '. <(pixdom --completion)';

    let existing = '';
    try {
      existing = readFileSync(rcFile, 'utf8');
    } catch {
      // file may not exist yet
    }

    const { updated, changed } = upsertRcLine(existing, sourceLine);
    if (changed) {
      writeFileSync(rcFile, updated, 'utf8');
      process.stdout.write(`✔ Completion added to ${rcFile}\n`);
    } else {
      process.stdout.write(`✔ Completion already present in ${rcFile}\n`);
    }
    process.stdout.write(`Run: source ${rcFile}\n`);
    return;
  }

  // Unknown shell — fall back to manual instructions
  process.stdout.write(
    [
      'pixdom shell completion setup',
      '',
      'Bash — add to ~/.bashrc:',
      "  echo '. <(pixdom --completion)' >> ~/.bashrc",
      '  source ~/.bashrc',
      '',
      'Zsh — add to ~/.zshrc:',
      "  echo 'source <(pixdom --completion)' >> ~/.zshrc",
      '  source ~/.zshrc',
      '',
      'Fish — write to completions directory:',
      '  pixdom --completion-fish > ~/.config/fish/completions/pixdom.fish',
      '',
      "Note: type 'pixdom' in full to trigger completion. Partial name expansion (pix<TAB> → pixdom) is not supported.",
      '',
    ].join('\n'),
  );
}

/**
 * Detects which subcommand is present in the full COMP_LINE.
 */
function detectSubcommand(line: string): 'convert' | 'completion' | 'mcp' | null {
  for (const token of line.trim().split(/\s+/)) {
    if (token === 'convert' || token === 'completion' || token === 'mcp') return token;
  }
  return null;
}

/**
 * Returns completion candidates based on the previous word and the full command line.
 *
 * Three-layer logic:
 *   Layer 1 — subcommands (prev === 'pixdom')
 *   Layer 2 — flag names (prev is subcommand or boolean flag → flag position)
 *   Layer 3 — flag values (prev is a value-taking flag → return its values)
 *
 * For the convert subcommand, already-used flags are filtered from suggestions
 * by parsing all '--*' tokens in fullLine.
 */
function getCompletionsForContext(prev: string, fullLine: string): string[] {
  // Layer 1: top-level subcommand selection
  if (prev === 'pixdom') return ['convert', 'completion', 'mcp'];

  const subcommand = detectSubcommand(fullLine);

  // Non-convert contexts: simple prev-only dispatch
  if (subcommand !== 'convert') {
    if (prev === 'completion') return ['--install', '--help'];
    if (prev === 'mcp') return ['--install', '--uninstall', '--status', '--set-key', '--help'];
    return [];
  }

  // Convert context — Layer 3: value position
  if (VALUE_TAKING_FLAGS.has(prev)) {
    switch (prev) {
      case '--profile':  return PROFILE_SLUGS;
      case '--format':   return FORMAT_VALUES;
      default:           return []; // free-text or file path: no enumerable values
    }
  }

  // Convert context — Layer 2: flag position
  // prev is a boolean flag, a consumed value, or 'convert' itself.
  // Return all convert flags minus any already present in the line.
  const usedFlags = new Set(fullLine.trim().split(/\s+/).filter(t => t.startsWith('--')));
  return CONVERT_FLAGS.filter(f => !usedFlags.has(f));
}

/**
 * Registers omelette-based shell completion and the `pixdom completion` subcommand.
 *
 * Must be called BEFORE program.parse() so that omelette can intercept completion
 * requests (--compgen, --completion, --completion-fish) before Commander processes argv.
 */
export function registerCompletion(program: Command): void {
  // Intercept --completion before omelette instantiation: use our generateCompletionScript()
  // output instead of omelette's internal hardcoded bash/zsh script.
  if (process.argv.includes('--completion')) {
    process.stdout.write(generateCompletionScript('pixdom') + '\n');
    process.exit(0);
  }

  // Intercept --completion-fish before omelette instantiation: omelette's built-in fish
  // output does not include -F (force-files) for --file/--image, so we generate our own.
  if (process.argv.includes('--completion-fish')) {
    process.stdout.write(generateFishCompletionScript());
    process.exit(0);
  }

  // Instantiating omelette calls checkInstall() internally: if --completion is in argv,
  // it outputs the bash/zsh init script and exits immediately.
  const args = process.argv;
  const compgenIdx = args.indexOf('--compgen');
  if (compgenIdx !== -1) {
    const prev = args[compgenIdx + 2] ?? '';
    const fullLine = args[compgenIdx + 3] ?? '';
    const completions = getCompletionsForContext(prev, fullLine);
    process.stdout.write(completions.join('\n') + '\n');
    process.exit(0);
  }

  const completion = omelette('pixdom <command>');

  completion.tree({
    convert: Object.fromEntries([
      ...CONVERT_FLAGS.filter((f) => f !== '--profile' && f !== '--format').map((f) => [f, []]),
      ['--profile', PROFILE_SLUGS],
      ['--format', FORMAT_VALUES],
    ]),
    completion: { '--install': [] },
    mcp: {
      '--install': [],
      '--uninstall': [],
      '--status': [],
      '--set-key': [],
      '--help': [],
    },
  });

  // Detect completion context before init() so we can exit cleanly if init() crashes.
  // omelette injects --compbash/--compzsh/--compgen/--compfish into argv during TAB expansion.
  const OMELETTE_FLAGS = ['--compbash', '--compzsh', '--compgen', '--compfish'];
  const isCompletionRequest = OMELETTE_FLAGS.some((f) => process.argv.includes(f));

  // Intercepts --compgen N <word> <line...> injected by the shell during TAB expansion.
  // Outputs completions and exits; no-op in normal execution.
  // try/catch: omelette's tree traversal crashes when flag values appear alongside --file/--image
  // (reduce() walks the tree with flag names as keys; a bare value hits undefined and throws).
  try {
    completion.init();
  } catch {
    // ignore crash
  }

  // Guard: if init() crashed before calling process.exit(), exit now so Commander never
  // sees --compbash/--compzsh/--compgen as unknown options.
  if (isCompletionRequest) {
    process.stdout.write('\n');
    process.exit(0);
  }

  program
    .command('completion')
    .description('Print shell completion script to stdout')
    .option('--install', 'Auto-install completion into your shell rc file')
    .action((opts: { install?: boolean }) => {
      if (opts.install) {
        installCompletion();
        process.exit(0);
      } else {
        process.stdout.write(generateCompletionScript('pixdom') + '\n');
        process.exit(0);
      }
    });
}
